# Generated by Django 4.1.2 on 2022-10-12 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HassPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_perm', models.BooleanField(default=False)),
                ('pass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password.orgpassword')),
                ('share_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
